import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import Image from "next/image";
import optusIcon from "../../public/optus-icon.png";
import CheckIcon from "@mui/icons-material/Check";
import InfoIcon from "@mui/icons-material/Info";
import ArrowDropDownIcon from "@mui/icons-material/ArrowDropDown";
import CameraAltIcon from "@mui/icons-material/CameraAlt";
import AddIcon from "@mui/icons-material/Add";
import InsertPhotoIcon from "@mui/icons-material/InsertPhoto";
import MicIcon from "@mui/icons-material/Mic";
import SentimentSatisfiedAltIcon from "@mui/icons-material/SentimentSatisfiedAlt";
import SendIcon from "@mui/icons-material/Send";
import { useState } from "react";
import { processQuestion } from "@/utils/processQuestions";

interface messageInterface {
  user: string;
  message: string;
}

export default function Home() {
  const [message, setMessage] = useState("");
  const [messages, setMessages] = useState<messageInterface[]>([]);

  const sendMessage = () => {
    const messageData = {
      user: "user",
      message,
    };
    setMessages((prevMessages) => [...prevMessages, messageData]);
    setMessage("");
    const botResponse = processQuestion(message);
    if (botResponse) {
      const botMessage = {
        user: "bot",
        message: botResponse,
      };
      setMessages((prevMessages) => [...prevMessages, botMessage]);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.chatbot}>
        <div className={styles.chatbot_container}>
          <div className={styles.chat_header}>
            <ArrowBackIcon />
            <div className={styles.chat_header_user}>
              <Image src={optusIcon} alt="" />
              <div className={styles.chat_header_user_info}>
                <h2>Optus</h2>
                <span>Tipically replies in a day</span>
              </div>
            </div>
            <div className={styles.verify_user}>
              <CheckIcon />
              <ArrowDropDownIcon />
            </div>
            <InfoIcon />
          </div>

          <div className={styles.chat_user}>
            <Image src={optusIcon} alt="" />
            <div className={styles.chat_user_info}>
              <h2>
                Optus <CheckIcon />
              </h2>
              <span>
                419k peopple like this including Maha Mourad and 35 friends
              </span>
              <span>Company</span>
            </div>
          </div>

          <div className={styles.chat_messages}>
            <span className={styles.chat_time}>11:05 AM</span>

            {messages.map((e) => (
              <div
                className={
                  e.user === "user" ? styles.message_own : styles.message
                }
                key={e.user}
              >
                <p>{e.message}</p>
              </div>
            ))}
          </div>

          <div className={styles.chat_type_messages}>
            <AddIcon className={styles.add_icon} />
            <CameraAltIcon />
            <InsertPhotoIcon />
            <MicIcon />
            <div className={styles.input_message}>
              <input
                type="text"
                placeholder="Aa"
                className={styles.input_message}
                onChange={(e) => setMessage(e.target.value)}
                value={message}
              />
              <SentimentSatisfiedAltIcon />
            </div>
            <button className={styles.send_message} onClick={sendMessage}>
              <SendIcon />
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
